### Read all movies with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read a single movie
GET {{baseUrl}}/movies/2

### Read all movies shorter or equal to 100 minutes
GET {{baseUrl}}/movies/?duration-max=100

### Add a movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title":"Les Schtroumpfs 2",
    "director":"Peyo",
    "duration": 107
}